package com.mfhsapp.test.enums;

public enum AttributeType {
	LENDER_CHECK_UNCHECK_AND_BB_RADIO,
	LENDER_NUM_VALUE_AND_BB_FREETEXT,
	LENDER_NUM_VALUE_AND_BB_RADIO,
	LENDER_NUM_RANGE_AND_BB_RADIO,
	LENDER_NUM_RANGE_AND_BB_FREETEXT,
	LENDER_DATE_RANGE_AND_BB_RADIO,
	LENDER_DATE_RANGE_AND_BB_DATE,
	LENDER_DATE_AND_BB_RADIO,
	LENDER_DATE_AND_BB_DATE,
	LENDER_MIX_AND_BB_RADIO
}
